Warning: truncated output (original token count: 95034)
Total output lines: 945

// ==UserScript==
// @name         10漫画—重制版
// @namespace    urn:10comic:remastered
// @version      2.0.8
// @description  漫画章节下载、搜索与自定义规则工具（液体玻璃 UI 重制版）
// @run-at       document-start
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        GM_setClipboard
// @grant        GM_info
// @grant        GM_xmlhttpRequest
// @grant        GM_addStyle
// @grant        GM_download
// @grant        GM_openInTab
// @grant        GM_registerMenuCommand
// @grant        GM_notification
// @grant        unsafeWindow
// @license      GPLv3
// @match        *://*/*
// @connect      *
// @noframes
// ==/UserScript==

/* HIPMH_READER_WORKER_START */
(()=>{
  const prefix="tenComicHipmhWorker:";
  if(location.hostname!=="reader.hipmh.top")return;
  const match=String(location.hash||"").match(/(?:^#|&)tencomic-task=([^&]+)/);
  if(!match)return;
  const taskId=match[1];
  const key=prefix+taskId;
  const wait=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));
  const run=async()=>{
    try{
      const initial=GM_getValue(key,null);
      if(!initial||initial.id!==taskId||initial.cancelled)return;
      const deadline=Date.now()+12e4;
      while(Date.now()<deadline){
        const record=GM_getValue(key,null);
        if(!record||record.id!==taskId||record.cancelled)return;
        const root=document.getElementById("chapcontent");
        if(root){
          const total=Math.max(0,Number(root.getAttribute("data-total-images"))||0);
          const images=[...new Set([...root.querySelectorAll(".chapter-image[data-src]")]
            .map(image=>String(image.getAttribute("data-src")||"").trim())
            .filter(url=>/^https:\/\//i.test(url)))];
          if(images.length&&(!total||images.length>=total)){
            GM_setValue(key,{...record,status:"ready",images,updatedAt:Date.now()});
            return;
          }
        }
        await wait(250);
      }
      const record=GM_getValue(key,null);
      record&&GM_setValue(key,{...record,status:"error",error:"HipMH 阅读页图片加载超时",updatedAt:Date.now()});
    }catch(error){
      const record=GM_getValue(key,null);
      record&&GM_setValue(key,{...record,status:"error",error:String(error&&error.message||error||"HipMH 阅读页处理失败"),updatedAt:Date.now()});
    }finally{
      try{window.close()}catch(error){}
    }
  };
  const start=()=>{window.__tenComicHipmhWorkerPromise=run()};
  "loading"===document.readyState?document.addEventListener("DOMContentLoaded",start,{once:true}):start();
})();
/* HIPMH_READER_WORKER_END */

/* KAKAOPAGE_READER_WORKER_START */
(()=>{
  const prefix="tenComicKakaoWorker:";
  if(location.hostname!=="page.kakao.com"||!/\/viewer\//.test(location.pathname))return;
  const match=String(location.hash||"").match(/(?:^#|&)tencomic-kakao-task=([^&]+)/);
  if(!match)return;
  const taskId=match[1];
  const key=prefix+taskId;
  const task=GM_getValue(key,null);
  if(!task||task.id!==taskId||task.cancelled||!String(task.readerUrl||"").includes(location.pathname))return;

  // The response-observation pattern is adapted from the GPL-3.0-only
  // "KakaoPage Downloader" userscript by ozler365. No request or unlock is forged.
  const findImageData=(value,depth=0)=>{
    if(!value||"object"!==typeof value||depth>8)return null;
    if(value.imageDownloadData&&Array.isArray(value.imageDownloadData.files))return value.imageDownloadData;
    for(const child of Object.values(value)){
      const found=findImageData(child,depth+1);
      if(found)return found;
    }
    return null;
  };
  let timeoutId=null;
  const publish=value=>{
    const record=GM_getValue(key,null);
    if(!record||record.id!==taskId||record.cancelled||record.status!=="waiting")return;
    const imageData=findImageData(value);
    if(!imageData)return;
    const ordered=imageData.files.map((file,index)=>({
      url:String(file&&(
        file.secureUrl||file.url||file.imageUrl
      )||"").trim(),
      order:Number(file&&(file.no??file.order??file.sortOrder))||index+1,
    })).filter(item=>/^https:\/\//i.test(item.url)).sort((a,b)=>a.order-b.order);
    const images=[...new Set(ordered.map(item=>item.url))];
    if(!images.length)return;
    timeoutId&&clearTimeout(timeoutId);
    GM_setValue(key,{...record,status:"ready",images,title:String(imageData.title||"KakaoPage 章节").trim(),updatedAt:Date.now()});
  };
  const parseAndPublish=text=>{
    if(!String(text||"").includes("imageDownloadData"))return;
    try{publish(JSON.parse(text))}catch(error){}
  };

  if("undefined"!==typeof XMLHttpRequest&&XMLHttpRequest.prototype){
    const originalOpen=XMLHttpRequest.prototype.open;
    XMLHttpRequest.prototype.open=function(){
      this.addEventListener("load",()=>{
        try{parseAndPublish(this.responseText)}catch(error){}
      });
      return originalOpen.apply(this,arguments);
    };
  }
  if("function"===typeof window.fetch){
    const originalFetch=window.fetch;
    window.fetch=function(...args){
      return originalFetch.apply(this,args).then(response=>{
        try{
          const clone=response.clone();
          clone.text().then(parseAndPublish).catch(()=>{});
        }catch(error){}
        return response;
      });
    };
  }
  timeoutId=setTimeout(()=>{
    const record=GM_getValue(key,null);
    record&&record.id===taskId&&record.status==="waiting"&&GM_setValue(key,{...record,status:"error",error:"KakaoPage 阅读器未返回可下载图片；请确认章节免费或当前账号已有访问权限",updatedAt:Date.now()});
  },9e4);
})();
/* KAKAOPAGE_READER_WORKER_END */

/* RIDIBOOKS_READER_WORKER_START */
(()=>{
  const prefix="tenComicRidiWorker:";
  if(location.hostname!=="ridibooks.com")return;
  const match=String(location.hash||"").match(/(?:^#|&)tencomic-ridi-task=([^&]+)/);
  if(!match)return;
  const taskId=match[1],key=prefix+taskId,task=GM_getValue(key,null);
  if(!task||task.id!==taskId||task.cancelled||!String(task.readerUrl||"").includes(location.pathname))return;

  // Independently implemented from the response-observation concept documented
  // by ozler365's Ridibooks Comic Ripper; no DRM, cookie, or unlock mechanism is used.
  let timeoutId=null;
  const publish=data=>{
    const record=GM_getValue(key,null);
    if(!record||record.id!==taskId||record.cancelled||record.status!=="waiting")return;
    const pages=data&&data.data&&Array.isArray(data.data.pages)?data.data.pages:[];
    const images=[...new Set(pages.map(page=>{
      if("string"===typeof page)return page;
      return page&&("string"===typeof page.src?page.src:"string"===typeof page.url?page.url:"string"===typeof page.image?page.image:"");
    }).filter(url=>/^https:\/\//i.test(String(url))))];
    if(!images.length)return;
    timeoutId&&clearTimeout(timeoutId);
    GM_setValue(key,{...record,status:"ready",images,title:String(data.data.book_title||"RidiBooks 章节").trim(),updatedAt:Date.now()});
  };
  const parseAndPublish=text=>{
    try{String(text||"").includes("pages")&&publish(JSON.parse(text))}catch(error){}
  };
  if("undefined"!==typeof XMLHttpRequest&&XMLHttpRequest.prototype){
    const originalOpen=XMLHttpRequest.prototype.open;
    XMLHttpRequest.prototype.open=function(method,url){
      this.addEventListener("load",()=>{
        try{String(url||"").includes("generate")&&parseAndPublish(this.responseText)}catch(error){}
      });
      return originalOpen.apply(this,arguments);
    };
  }
  if("function"===typeof window.fetch){
    const originalFetch=window.fetch;
    window.fetch=function(...args){
      return originalFetch.apply(this,args).then(response=>{
        try{
          const url="string"===typeof args[0]?args[0]:args[0]&&args[0].url;
          String(url||"").includes("generate")&&response.clone().json().then(publish).catch(()=>{});
        }catch(error){}
        return response;
      });
    };
  }
  timeoutId=setTimeout(()=>{
    const record=GM_getValue(key,null);
    record&&record.id===taskId&&record.status==="waiting"&&GM_setValue(key,{...record,status:"error",error:"RidiBooks 阅读器未返回可下载图片；请确认章节免费或当前账号已有访问权限",updatedAt:Date.now()});
  },9e4);
})();
/* RIDIBOOKS_READER_WORKER_END */

(()=>{var __webpack_modules__={733:(e,t,n)=>{e.exports=function e(t,n,r){function a(o,s){if(!n[o]){if(!t[o]){if(i)return i(o,!0);var c=new Error("Cannot find module '"+o+"'");throw c.code="MODULE_NOT_FOUND",c}var d=n[o]={exports:{}};t[o][0].call(d.exports,function(e){return a(t[o][1][e]||e)},d,d.exports,e,t,n,r)}return n[o].exports}for(var i=void 0,o=0;o<r.length;o++)a(r[o]);return a}({1:[function(e,t,n){"use strict"
;var r=e("./utils"),a=e("./support"),i="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";n.encode=function(e){for(var t,n,a,o,s,c,d,l=[],u=0,p=e.length,h=p,m="string"!==r.getTypeOf(e);u<e.length;)h=p-u,a=m?(t=e[u++],n=u<p?e[u++]:0,u<p?e[u++]:0):(t=e.charCodeAt(u++),n=u<p?e.charCodeAt(u++):0,u<p?e.charCodeAt(u++):0),o=t>>2,s=(3&t)<<4|n>>4,c=1<h?(15&n)<<2|a>>6:64,d=2<h?63&a:64,l.push(i.charAt(o)+i.charAt(s)+i.charAt(c)+i.charAt(d));return l.join("")},n.decode=function(e){
var t,n,r,o,s,c,d=0,l=0,u="data:";if(e.substr(0,5)===u)throw new Error("Invalid base64 input, it looks like a data url.");var p,h=3*(e=e.replace(/[^A-Za-z0-9\+\/\=]/g,"")).length/4;if(e.charAt(e.length-1)===i.charAt(64)&&h--,e.charAt(e.length-2)===i.charAt(64)&&h--,h%1!=0)throw new Error("Invalid base64 input, bad content length.");for(p=a.uint8array?new Uint8Array(0|h):new Array(0|h);d<e.length;)t=i.indexOf(e.charAt(d++))<<2|(o=i.indexOf(e.charAt(d++)))>>4,
n=(15&o)<<4|(s=i.indexOf(e.charAt(d++)))>>2,r=(3&s)<<6|(c=i.indexOf(e.charAt(d++))),p[l++]=t,64!==s&&(p[l++]=n),64!==c&&(p[l++]=r);return p}},{"./support":30,"./utils":32}],2:[function(e,t,n){"use strict";var r=e("./external"),a=e("./stream/DataWorker"),i=e("./stream/Crc32Probe"),o=e("./stream/DataLengthProbe");function s(e,t,n,r,a){this.compressedSize=e,this.uncompressedSize=t,this.crc32=n,this.compression=r,this.compressedContent=a}s.prototype={getContentWorker:function(){
var e=new a(r.Promise.resolve(this.compressedContent)).pipe(this.compression.uncompressWorker()).pipe(new o("data_length")),t=this;return e.on("end",function(){if(this.streamInfo.data_length!==t.uncompressedSize)throw new Error("Bug : uncompressed data size mismatch")}),e},getCompressedWorker:function(){
return new a(r.Promise.resolve(this.compressedContent)).withStreamInfo("compressedSize",this.compressedSize).withStreamInfo("uncompressedSize",this.uncompressedSize).withStreamInfo("crc32",this.crc32).withStreamInfo("compression",this.compression)}},s.createWorkerFrom=function(e,t,n){return e.pipe(new i).pipe(new o("uncompressedSize")).pipe(t.compressWorker(n)).pipe(new o("compressedSize")).withStreamInfo("compression",t)},t.exports=s},{"./external":6,"./stream/Crc32Probe":25,
"./stream/DataLengthProbe":26,"./stream/DataWorker":27}],3:[function(e,t,n){"use strict";var r=e("./stream/GenericWorker");n.STORE={magic:"\0\0",compressWorker:function(e){return new r("STORE compression")},uncompressWorker:function(){return new r("STORE decompression")}},n.DEFLATE=e("./flate")},{"./flate":7,"./stream/GenericWorker":28}],4:[function(e,t,n){"use strict";var r=e("./utils"),a=function(){for(var e,t=[],n=0;n<256;n++){e=n;for(var r=0;r<8;r++)e=1&e?3988292384^e>>>1:e>>>1;t[n]=e}
return t}();t.exports=function(e,t){return void 0!==e&&e.length?"string"!==r.getTypeOf(e)?function(e,t,n){var r=a,i=0+n;e^=-1;for(var o=0;o<i;o++)e=e>>>8^r[255&(e^t[o])];return-1^e}(0|t,e,e.length):function(e,t,n){var r=a,i=0+n;e^=-1;for(var o=0;o<i;o++)e=e>>>8^r[255&(e^t.charCodeAt(o))];return-1^e}(0|t,e,e.length):0}},{"./utils":32}],5:[function(e,t,n){"use strict";n.base64=!1,n.binary=!1,n.dir=!1,n.createFolders=!0,n.date=null,n.compression=null,n.compressionOptions=null,n.comment=null,
n.unixPermissions=null,n.dosPermissions=null},{}],6:[function(e,t,n){"use strict";var r;r="undefined"!=typeof Promise?Promise:e("lie"),t.exports={Promise:r}},{lie:37}],7:[function(e,t,n){"use strict";var r="undefined"!=typeof Uint8Array&&"undefined"!=typeof Uint16Array&&"undefined"!=typeof Uint32Array,a=e("pako"),i=e("./utils"),o=e("./stream/GenericWorker"),s=r?"uint8array":"array";function c(e,t){o.call(this,"FlateWorker/"+e),this._pako=null,this._pakoAction=e,this._pakoOptions=t,this.meta={}}
n.magic="\b\0",i.inherits(c,o),c.prototype.processChunk=function(e){this.meta=e.meta,null===this._pako&&this._createPako(),this._pako.push(i.transformTo(s,e.data),!1)},c.prototype.flush=function(){o.prototype.flush.call(this),null===this._pako&&this._createPako(),this._pako.push([],!0)},c.prototype.cleanUp=function(){o.prototype.cleanUp.call(this),this._pako=null},c.prototype._createPako=function(){this._pako=new a[this._pakoAction]({raw:!0,level:this._pakoOptions.level||-1});var e=this
;this._pako.onData=function(t){e.push({data:t,meta:e.meta})}},n.compressWorker=function(e){return new c("Deflate",e)},n.uncompressWorker=function(){return new c("Inflate",{})}},{"./stream/GenericWorker":28,"./utils":32,pako:38}],8:[function(e,t,n){"use strict";function r(e,t){var n,r="";for(n=0;n<t;n++)r+=String.fromCharCode(255&e),e>>>=8;return r}function a(e,t,n,a,o,l){
var u,p,h=e.file,m=e.compression,g=l!==s.utf8encode,b=i.transformTo("string",l(h.name)),f=i.transformTo("string",s.utf8encode(h.name)),x=h.comment,v=i.transformTo("string",l(x)),y=i.transformTo("string",s.utf8encode(x)),w=f.length!==h.name.length,k=y.length!==x.length,_="",E="",C="",S=h.dir,A=h.date,I={crc32:0,compressedSize:0,uncompressedSize:0};t&&!n||(I.crc32=e.crc32,I.compressedSize=e.compressedSize,I.uncompressedSize=e.uncompressedSize);var N=0;t&&(N|=8),g||!w&&!k||(N|=2048);var L=0,T=0
;S&&(L|=16),"UNIX"===o?(T=798,L|=function(e,t){var n=e;return e||(n=t?16893:33204),(65535&n)<<16}(h.unixPermissions,S)):(T=20,L|=function(e){return 63&(e||0)}(h.dosPermissions)),u=A.getUTCHours(),u<<=6,u|=A.getUTCMinutes(),u<<=5,u|=A.getUTCSeconds()/2,p=A.getUTCFullYear()-1980,p<<=4,p|=A.getUTCMonth()+1,p<<=5,p|=A.getUTCDate(),w&&(E=r(1,1)+r(c(b),4)+f,_+="up"+r(E.length,2)+E),k&&(C=r(1,1)+r(c(v),4)+y,_+="uc"+r(C.length,2)+C);var z="";return z+="\n\0",z+=r(N,2),z+=m.magic,z+=r(u,2),z+=r(p,2),
z+=r(I.crc32,4),z+=r(I.compressedSize,4),z+=r(I.uncompressedSize,4),z+=r(b.length,2),z+=r(_.length,2),{fileRecord:d.LOCAL_FILE_HEADER+z+b+_,dirRecord:d.CENTRAL_FILE_HEADER+r(T,2)+z+r(v.length,2)+"\0\0\0\0"+r(L,4)+r(a,4)+b+_+v}}var i=e("../utils"),o=e("../stream/GenericWorker"),s=e("../utf8"),c=e("../crc32"),d=e("../signature");function l(e,t,n,r){o.call(this,"ZipFileWorker"),this.bytesWritten=0,this.zipComment=t,this.zipPlatform=n,this.encodeFileName=r,this.streamFiles=e,this.accumulate=!1,
this.contentBuffer=[],this.dirRecords=[],this.currentSourceOffset=0,this.entriesCount=0,this.currentFile=null,this._sources=[]}i.inherits(l,o),l.prototype.push=function(e){var t=e.meta.percent||0,n=this.entriesCount,r=this._sources.length;this.accumulate?this.contentBuffer.push(e):(this.bytesWritten+=e.data.length,o.prototype.push.call(this,{data:e.data,meta:{currentFile:this.currentFile,percent:n?(t+100*(n-r-1))/n:100}}))},l.prototype.openedSource=function(e){
this.currentSourceOffset=this.bytesWritten,this.currentFile=e.file.name;var t=this.streamFiles&&!e.file.dir;if(t){var n=a(e,t,!1,this.currentSourceOffset,this.zipPlatform,this.encodeFileName);this.push({data:n.fileRecord,meta:{percent:0}})}else this.accumulate=!0},l.prototype.closedSource=function(e){this.accumulate=!1;var t=this.streamFiles&&!e.file.dir,n=a(e,t,!0,this.currentSourceOffset,this.zipPlatform,this.encodeFileName);if(this.dirRecords.push(n.dirRecord),t)this.push({data:function(e){
return d.DATA_DESCRIPTOR+r(e.crc32,4)+r(e.compressedSize,4)+r(e.uncompressedSize,4)}(e),meta:{percent:100}});else for(this.push({data:n.fileRecord,meta:{percent:0}});this.contentBuffer.length;)this.push(this.contentBuffer.shift());this.currentFile=null},l.prototype.flush=function(){for(var e=this.bytesWritten,t=0;t<this.dirRecords.length;t++)this.push({data:this.dirRecords[t],meta:{percent:100}});var n=this.bytesWritten-e,a=function(e,t,n,a,o){var s=i.transformTo("string",o(a))
;return d.CENTRAL_DIRECTORY_END+"\0\0\0\0"+r(e,2)+r(e,2)+r(t,4)+r(n,4)+r(s.length,2)+s}(this.dirRecords.length,n,e,this.zipComment,this.encodeFileName);this.push({data:a,meta:{percent:100}})},l.prototype.prepareNextSource=function(){this.previous=this._sources.shift(),this.openedSource(this.previous.streamInfo),this.isPaused?this.previous.pause():this.previous.resume()},l.prototype.registerPrevious=function(e){this._sources.push(e);var t=this;return e.on("data",function(e){t.processChunk(e)}),
e.on("end",function(){t.closedSource(t.previous.streamInfo),t._sources.length?t.prepareNextSource():t.end()}),e.on("error",function(e){t.error(e)}),this},l.prototype.resume=function(){return!!o.prototype.resume.call(this)&&(!this.previous&&this._sources.length?(this.prepareNextSource(),!0):this.previous||this._sources.length||this.generatedError?void 0:(this.end(),!0))},l.prototype.error=function(e){var t=this._sources;if(!o.prototype.error.call(this,e))return!1;for(var n=0;n<t.length;n++)try{
t[n].error(e)}catch(e){}return!0},l.prototype.lock=function(){o.prototype.lock.call(this);for(var e=this._sources,t=0;t<e.length;t++)e[t].lock()},t.exports=l},{"../crc32":4,"../signature":23,"../stream/GenericWorker":28,"../utf8":31,"../utils":32}],9:[function(e,t,n){"use strict";var r=e("../compressions"),a=e("./ZipFileWorker");n.generateWorker=function(e,t,n){var i=new a(t.streamFiles,n,t.platform,t.encodeFileName),o=0;try{e.forEach(function(e,n){o++;var a=function(e,t){var n=e||t,a=r[n]
;if(!a)throw new Error(n+" is not a valid compression method !");return a}(n.options.compression,t.compression),s=n.options.compressionOptions||t.compressionOptions||{},c=n.dir,d=n.date;n._compressWorker(a,s).withStreamInfo("file",{name:e,dir:c,date:d,comment:n.comment||"",unixPermissions:n.unixPermissions,dosPermissions:n.dosPermissions}).pipe(i)}),i.entriesCount=o}catch(e){i.error(e)}return i}},{"../compressions":3,"./ZipFileWorker":8}],10:[function(e,t,n){"use strict";function r(){
if(!(this instanceof r))return new r;if(arguments.length)throw new Error("The constructor with parameters has been removed in JSZip 3.0, please check the upgrade guide.");this.files=Object.create(null),this.comment=null,this.root="",this.clone=function(){var e=new r;for(var t in this)"function"!=typeof this[t]&&(e[t]=this[t]);return e}}(r.prototype=e("./object")).loadAsync=e("./load"),r.support=e("./support"),r.defaults=e("./defaults"),r.version="3.10.0",r.loadAsync=function(e,t){
return(new r).loadAsync(e,t)},r.external=e("./external"),t.exports=r},{"./defaults":5,"./external":6,"./load":11,"./object":15,"./support":30}],11:[function(e,t,n){"use strict";var r=e("./utils"),a=e("./external"),i=e("./utf8"),o=e("./zipEntries"),s=e("./stream/Crc32Probe"),c=e("./nodejsUtils");function d(e){return new a.Promise(function(t,n){var r=e.decompressed.getContentWorker().pipe(new s);r.on("error",function(e){n(e)}).on("end",function(){
r.streamInfo.crc32!==e.decompressed.crc32?n(new Error("Corrupted zip : CRC32 mismatch")):t()}).resume()})}t.exports=function(e,t){var n=this;return t=r.extend(t||{},{base64:!1,checkCRC32:!1,optimizedBinaryString:!1,createFolders:!1,decodeFileName:i.utf8decode}),c.isNode&&c.isStream(e)?a.Promise.reject(new Error("JSZip can't accept a stream when loading a zip file.")):r.prepareContent("the loaded zip file",e,!0,t.optimizedBinaryString,t.base64).then(function(e){var n=new o(t);return n.load(e),n
}).then(function(e){var n=[a.Promise.resolve(e)],r=e.files;if(t.checkCRC32)for(var i=0;i<r.length;i++)n.push(d(r[i]));return a.Promise.all(n)}).then(function(e){for(var a=e.shift(),i=a.files,o=0;o<i.length;o++){var s=i[o],c=s.fileNameStr,d=r.resolve(s.fileNameStr);n.file(d,s.decompressed,{binary:!0,optimizedBinaryString:!0,date:s.date,dir:s.dir,comment:s.fileCommentStr.length?s.fileCommentStr:null,unixPermissions:s.unixPermissions,dosPermissions:s.dosPermissions,createFolders:t.createFolders}),
s.dir||(n.file(d).unsafeOriginalName=c)}return a.zipComment.length&&(n.comment=a.zipComment),n})}},{"./external":6,"./nodejsUtils":14,"./stream/Crc32Probe":25,"./utf8":31,"./utils":32,"./zipEntries":33}],12:[function(e,t,n){"use strict";var r=e("../utils"),a=e("../stream/GenericWorker");function i(e,t){a.call(this,"Nodejs stream input adapter for "+e),this._upstreamEnded=!1,this._bindStream(t)}r.inherits(i,a),i.prototype._bindStream=function(e){var t=this;(this._stream=e).pause(),
e.on("data",function(e){t.push({data:e,meta:{percent:0}})}).on("error",function(e){t.isPaused?this.generatedError=e:t.error(e)}).on("end",function(){t.isPaused?t._upstreamEnded=!0:t.end()})},i.prototype.pause=function(){return!!a.prototype.pause.call(this)&&(this._stream.pause(),!0)},i.prototype.resume=function(){return!!a.prototype.resume.call(this)&&(this._upstreamEnded?this.end():this._stream.resume(),!0)},t.exports=i},{"../stream/GenericWorker":28,"../utils":32}],13:[function(e,t,n){
"use strict";var r=e("readable-stream").Readable;function a(e,t,n){r.call(this,t),this._helper=e;var a=this;e.on("data",function(e,t){a.push(e)||a._helper.pause(),n&&n(t)}).on("error",function(e){a.emit("error",e)}).on("end",function(){a.push(null)})}e("../utils").inherits(a,r),a.prototype._read=function(){this._helper.resume()},t.exports=a},{"../utils":32,"readable-stream":16}],14:[function(e,t,n){"use strict";t.exports={isNode:"undefined"!=typeof Buffer,newBufferFrom:function(e,t){
if(Buffer.from&&Buffer.from!==Uint8Array.from)return Buffer.from(e,t);if("number"==typeof e)throw new Error('The "data" argument must not be a number');return new Buffer(e,t)},allocBuffer:function(e){if(Buffer.alloc)return Buffer.alloc(e);var t=new Buffer(e);return t.fill(0),t},isBuffer:function(e){return Buffer.isBuffer(e)},isStream:function(e){return e&&"function"==typeof e.on&&"function"==typeof e.pause&&"function"==typeof e.resume}}},{}],15:[function(e,t,n){"use strict";function r(e,t,n){
var r,a=i.getTypeOf(t),s=i.extend(n||{},c);s.date=s.date||new Date,null!==s.compression&&(s.compression=s.compression.toUpperCase()),"string"==typeof s.unixPermissions&&(s.unixPermissions=parseInt(s.unixPermissions,8)),s.unixPermissions&&16384&s.unixPermissions&&(s.dir=!0),s.dosPermissions&&16&s.dosPermissions&&(s.dir=!0),s.dir&&(e=g(e)),s.createFolders&&(r=m(e))&&b.call(this,r,!0);var u="string"===a&&!1===s.binary&&!1===s.base64;n&&void 0!==n.binary||(s.binary=!u),
(t instanceof d&&0===t.uncompressedSize||s.dir||!t||0===t.length)&&(s.base64=!1,s.binary=!0,t="",s.compression="STORE",a="string");var f;f=t instanceof d||t instanceof o?t:p.isNode&&p.isStream(t)?new h(e,t):i.prepareContent(e,t,s.binary,s.optimizedBinaryString,s.base64);var x=new l(e,f,s);this.files[e]=x}
var a=e("./utf8"),i=e("./utils"),o=e("./stream/GenericWorker"),s=e("./stream/StreamHelper"),c=e("./defaults"),d=e("./compressedObject"),l=e("./zipObject"),u=e("./generate"),p=e("./nodejsUtils"),h=e("./nodejs/NodejsStreamInputAdapter"),m=function(e){"/"===e.slice(-1)&&(e=e.substring(0,e.length-1));var t=e.lastIndexOf("/");return 0<t?e.substring(0,t):""},g=function(e){return"/"!==e.slice(-1)&&(e+="/"),e},b=function(e,t){return t=void 0!==t?t:c.createFolders,e=g(e),
this.files[e]||r.call(this,e,null,{dir:!0,createFolders:t}),this.files[e]};function f(e){return"[object RegExp]"===Object.prototype.toString.call(e)}var x={load:function(){throw new Error("This method has been removed in JSZip 3.0, please check the upgrade guide.")},forEach:function(e){var t,n,r;for(t in this.files)r=this.files[t],(n=t.slice(this.root.length,t.length))&&t.slice(0,this.root.length)===this.root&&e(n,r)},filter:function(e){var t=[];return this.forEach(function(n,r){
e(n,r)&&t.push(r)}),t},file:function(e,t,n){if(1!==arguments.length)return e=this.root+e,r.call(this,e,t,n),this;if(f(e)){var a=e;return this.filter(function(e,t){return!t.dir&&a.test(e)})}var i=this.files[this.root+e];return i&&!i.dir?i:null},folder:function(e){if(!e)return this;if(f(e))return this.filter(function(t,n){return n.dir&&e.test(t)});var t=this.root+e,n=b.call(this,t),r=this.clone();return r.root=n.name,r},remove:function(e){e=this.root+e;var t=this.files[e]
;if(t||("/"!==e.slice(-1)&&(e+="/"),t=this.files[e]),t&&!t.dir)delete this.files[e];else for(var n=this.filter(function(t,n){return n.name.slice(0,e.length)===e}),r=0;r<n.length;r++)delete this.files[n[r].name];return this},generate:function(e){throw new Error("This method has been removed in JSZip 3.0, please check the upgrade guide.")},generateInternalStream:function(e){var t,n={};try{if((n=i.extend(e||{},{streamFiles:!1,compression:"STORE",compressionOptions:null,type:"",platform:"DOS",
comment:null,mimeType:"application/zip",encodeFileName:a.utf8encode})).type=n.type.toLowerCase(),n.compression=n.compression.toUpperCase(),"binarystring"===n.type&&(n.type="string"),!n.type)throw new Error("No output type specified.");i.checkSupport(n.type),"darwin"!==n.platform&&"freebsd"!==n.platform&&"linux"!==n.platform&&"sunos"!==n.platform||(n.platform="UNIX"),"win32"===n.platform&&(n.platform="DOS");var r=n.comment||this.comment||"";t=u.generateWorker(this,n,r)}catch(e){
(t=new o("error")).error(e)}return new s(t,n.type||"string",n.mimeType)},generateAsync:function(e,t){return this.generateInternalStream(e).accumulate(t)},generateNodeStream:function(e,t){return(e=e||{}).type||(e.type="nodebuffer"),this.generateInternalStream(e).toNodejsStream(t)}};t.exports=x},{"./compressedObject":2,"./defaults":5,"./generate":9,"./nodejs/NodejsStreamInputAdapter":12,"./nodejsUtils":14,"./stream/GenericWorker":28,"./stream/StreamHelper":29,"./utf8":31,"./utils":32,
"./zipObject":35}],16:[function(e,t,n){t.exports=e("stream")},{stream:void 0}],17:[function(e,t,n){"use strict";var r=e("./DataReader");function a(e){r.call(this,e);for(var t=0;t<this.data.length;t++)e[t]=255&e[t]}e("../utils").inherits(a,r),a.prototype.byteAt=function(e){return this.data[this.zero+e]},a.prototype.lastIndexOfSignature=function(e){
for(var t=e.charCodeAt(0),n=e.charCodeAt(1),r=e.charCodeAt(2),a=e.charCodeAt(3),i=this.length-4;0<=i;--i)if(this.data[i]===t&&this.data[i+1]===n&&this.data[i+2]===r&&this.data[i+3]===a)return i-this.zero;return-1},a.prototype.readAndCheckSignature=function(e){var t=e.charCodeAt(0),n=e.charCodeAt(1),r=e.charCodeAt(2),a=e.charCodeAt(3),i=this.readData(4);return t===i[0]&&n===i[1]&&r===i[2]&&a===i[3]},a.prototype.readData=function(e){if(this.checkOffset(e),0===e)return[]
;var t=this.data.slice(this.zero+this.index,this.zero+this.index+e);return this.index+=e,t},t.exports=a},{"../utils":32,"./DataReader":18}],18:[function(e,t,n){"use strict";var r=e("../utils");function a(e){this.data=e,this.length=e.length,this.index=0,this.zero=0}a.prototype={checkOffset:function(e){this.checkIndex(this.index+e)},checkIndex:function(e){if(this.length<this.zero+e||e<0)throw new Error("End of data reached (data length = "+this.length+", asked index = "+e+"). Corrupted zip ?")},
setIndex:function(e){this.checkIndex(e),this.index=e},skip:function(e){this.setIndex(this.index+e)},byteAt:function(e){},readInt:function(e){var t,n=0;for(this.checkOffset(e),t=this.index+e-1;t>=this.index;t--)n=(n<<8)+this.byteAt(t);return this.index+=e,n},readString:function(e){return r.transformTo("string",this.readData(e))},readData:function(e){},lastIndexOfSignature:function(e){},readAndCheckSignature:function(e){},readDate:function(){var e=this.readInt(4)
;return new Date(Date.UTC(1980+(e>>25&127),(e>>21&15)-1,e>>16&31,e>>11&31,e>>5&63,(31&e)<<1))}},t.exports=a},{"../utils":32}],19:[function(e,t,n){"use strict";var r=e("./Uint8ArrayReader");function a(e){r.call(this,e)}e("../utils").inherits(a,r),a.prototype.readData=function(e){this.checkOffset(e);var t=this.data.slice(this.zero+this.index,this.zero+this.index+e);return this.index+=e,t},t.exports=a},{"../utils":32,"./Uint8ArrayReader":21}],20:[function(e,t,n){"use strict";var r=e("./DataReader")
;function a(e){r.call(this,e)}e("../utils").inherits(a,r),a.prototype.byteAt=function(e){return this.data.charCodeAt(this.zero+e)},a.prototype.lastIndexOfSignature=function(e){return this.data.lastIndexOf(e)-this.zero},a.prototype.readAndCheckSignature=function(e){return e===this.readData(4)},a.prototype.readData=function(e){this.checkOffset(e);var t=this.data.slice(this.zero+this.index,this.zero+this.index+e);return this.index+=e,t},t.exports=a},{"../utils":32,"./DataReader":18}],
21:[function(e,t,n){"use strict";var r=e("./ArrayReader");function a(e){r.call(this,e)}e("../utils").inherits(a,r),a.prototype.readData=function(e){if(this.checkOffset(e),0===e)return new Uint8Array(0);var t=this.data.subarray(this.zero+this.index,this.zero+this.index+e);return this.index+=e,t},t.exports=a},{"../utils":32,"./ArrayReader":17}],22:[function(e,t,n){"use strict"
;var r=e("../utils"),a=e("../support"),i=e("./ArrayReader"),o=e("./StringReader"),s=e("./NodeBufferReader"),c=e("./Uint8ArrayReader");t.exports=function(e){var t=r.getTypeOf(e);return r.checkSupport(t),"string"!==t||a.uint8array?"nodebuffer"===t?new s(e):a.uint8array?new c(r.transformTo("uint8array",e)):new i(r.transformTo("array",e)):new o(e)}},{"../support":30,"../utils":32,"./ArrayReader":17,"./NodeBufferReader":19,"./StringReader":20,"./Uint8ArrayReader":21}],23:[function(e,t,n){"use strict"
;n.LOCAL_FILE_HEADER="PK",n.CENTRAL_FILE_HEADER="PK",n.CENTRAL_DIRECTORY_END="PK",n.ZIP64_CENTRAL_DIRECTORY_LOCATOR="PK",n.ZIP64_CENTRAL_DIRECTORY_END="PK",n.DATA_DESCRIPTOR="PK\b"},{}],24:[function(e,t,n){"use strict";var r=e("./GenericWorker"),a=e("../utils");function i(e){r.call(this,"ConvertWorker to "+e),this.destType=e}a.inherits(i,r),i.prototype.processChunk=function(e){this.push({data:a.transformTo(this.destType,e.data),meta:e.meta})},t.exports=i},{"../utils":32,
"./GenericWorker":28}],25:[function(e,t,n){"use strict";var r=e("./GenericWorker"),a=e("../crc32");function i(){r.call(this,"Crc32Probe"),this.withStreamInfo("crc32",0)}e("../utils").inherits(i,r),i.prototype.processChunk=function(e){this.streamInfo.crc32=a(e.data,this.streamInfo.crc32||0),this.push(e)},t.exports=i},{"../crc32":4,"../utils":32,"./GenericWorker":28}],26:[function(e,t,n){"use strict";var r=e("../utils"),a=e("./GenericWorker");function i(e){a.call(this,"DataLengthProbe for "+e),
this.propName=e,this.withStreamInfo(e,0)}r.inherits(i,a),i.prototype.processChunk=function(e){if(e){var t=this.streamInfo[this.propName]||0;this.streamInfo[this.propName]=t+e.data.length}a.prototype.processChunk.call(this,e)},t.exports=i},{"../utils":32,"./GenericWorker":28}],27:[function(e,t,n){"use strict";var r=e("../utils"),a=e("./GenericWorker");function i(e){a.call(this,"DataWorker");var t=this;this.dataIsReady=!1,this.index=0,this.max=0,this.data=null,this.type="",this._tickScheduled=!1,
e.then(function(e){t.dataIsReady=!0,t.data=e,t.max=e&&e.length||0,t.type=r.getTypeOf(e),t.isPaused||t._tickAndRepeat()},function(e){t.error(e)})}r.inherits(i,a),i.prototype.cleanUp=function(){a.prototype.cleanUp.call(this),this.data=null},i.prototype.resume=function(){return!!a.prototype.resume.call(this)&&(!this._tickScheduled&&this.dataIsReady&&(this._tickScheduled=!0,r.delay(this._tickAndRepeat,[],this)),!0)},i.prototype._tickAndRepeat=function(){this._tickScheduled=!1,
this.isPaused||this.isFinished||(this._tick(),this.isFinished||(r.delay(this._tickAndRepeat,[],this),this._tickScheduled=!0))},i.prototype._tick=function(){if(this.isPaused||this.isFinished)return!1;var e=null,t=Math.min(this.max,this.index+16384);if(this.index>=this.max)return this.end();switch(this.type){case"string":e=this.data.substring(this.index,t);break;case"uint8array":e=this.data.subarray(this.index,t);break;case"array":case"nodebuffer":e=this.data.slice(this.index,t)}
return this.index=t,this.push({data:e,meta:{percent:this.max?this.index/this.max*100:0}})},t.exports=i},{"../utils":32,"./GenericWorker":28}],28:[function(e,t,n){"use strict";function r(e){this.name=e||"default",this.streamInfo={},this.generatedError=null,this.extraStreamInfo={},this.isPaused=!0,this.isFinished=!1,this.isLocked=!1,this._listeners={data:[],end:[],error:[]},this.previous=null}r.prototype={push:function(e){this.emit("data",e)},end:function(){if(this.isFinished)return!1;this.flush()
;try{this.emit("end"),this.cleanUp(),this.isFinished=!0}catch(e){this.emit("error",e)}return!0},error:function(e){return!this.isFinished&&(this.isPaused?this.generatedError=e:(this.isFinished=!0,this.emit("error",e),this.previous&&this.previous.error(e),this.cleanUp()),!0)},on:function(e,t){return this._listeners[e].push(t),this},cleanUp:function(){this.streamInfo=this.generatedError=this.extraStreamInfo=null,this._listeners=[]},emit:function(e,t){
if(this._listeners[e])for(var n=0;n<this._listeners[e].length;n++)this._listeners[e][n].call(this,t)},pipe:function(e){return e.registerPrevious(this)},registerPrevious:function(e){if(this.isLocked)throw new Error("The stream '"+this+"' has already been used.");this.streamInfo=e.streamInfo,this.mergeStreamInfo(),this.previous=e;var t=this;return e.on("data",function(e){t.processChunk(e)}),e.on("end",function(){t.end()}),e.on("error",function(e){t.error(e)}),this},pause:function(){
return!this.isPaused&&!this.isFinished&&(this.isPaused=!0,this.previous&&this.previous.pause(),!0)},resume:function(){if(!this.isPaused||this.isFinished)return!1;var e=this.isPaused=!1;return this.generatedError&&(this.error(this.generatedError),e=!0),this.previous&&this.previous.resume(),!e},flush:function(){},processChunk:function(e){this.push(e)},withStreamInfo:function(e,t){return this.extraStreamInfo[e]=t,this.mergeStreamInfo(),this},mergeStreamInfo:function(){
for(var e in this.extraStreamInfo)this.extraStreamInfo.hasOwnProperty(e)&&(this.streamInfo[e]=this.extraStreamInfo[e])},lock:function(){if(this.isLocked)throw new Error("The stream '"+this+"' has already been used.");this.isLocked=!0,this.previous&&this.previous.lock()},toString:function(){var e="Worker "+this.name;return this.previous?this.previous+" -> "+e:e}},t.exports=r},{}],29:[function(e,t,n){"use strict"
;var r=e("../utils"),a=e("./ConvertWorker"),i=e("./GenericWorker"),o=e("../base64"),s=e("../support"),c=e("../external"),d=null;if(s.nodestream)try{d=e("../nodejs/NodejsStreamOutputAdapter")}catch(e){}function l(e,t,n){var o=t;switch(t){case"blob":case"arraybuffer":o="uint8array";break;case"base64":o="string"}try{this._internalType=o,this._outputType=t,this._mimeType=n,r.checkSupport(o),this._worker=e.pipe(new a(o)),e.lock()}catch(e){this._worker=new i("error"),this._worker.error(e)}}
l.prototype={accumulate:function(e){return function(e,t){return new c.Promise(function(n,a){var i=[],s=e._internalType,c=e._outputType,d=e._mimeType;e.on("data",function(e,n){i.push(e),t&&t(n)}).on("error",function(e){i=[],a(e)}).on("end",function(){try{var e=function(e,t,n){switch(e){case"blob":return r.newBlob(r.transformTo("arraybuffer",t),n);case"base64":return o.encode(t);default:return r.transformTo(e,t)}}(c,function(e,t){var n,r=0,a=null,i=0;for(n=0;n<t.length;n++)i+=t[n].length
;switch(e){case"string":return t.join("");case"array":return Array.prototype.concat.apply([],t);case"uint8array":for(a=new Uint8Array(i),n=0;n<t.length;n++)a.set(t[n],r),r+=t[n].length;return a;case"nodebuffer":return Buffer.concat(t);default:throw new Error("concat : unsupported type '"+e+"'")}}(s,i),d);n(e)}catch(e){a(e)}i=[]}).resume()})}(this,e)},on:function(e,t){var n=this;return"data"===e?this._worker.on(e,function(e){t.call(n,e.data,e.meta)}):this._worker.on(e,function(){
r.delay(t,arguments,n)}),this},resume:function(){return r.delay(this._worker.resume,[],this._worker),this},pause:function(){return this._worker.pause(),this},toNodejsStream:function(e){if(r.checkSupport("nodestream"),"nodebuffer"!==this._outputType)throw new Error(this._outputType+" is not supported by this method");return new d(this,{objectMode:"nodebuffer"!==this._outputType},e)}},t.exports=l},{"../base64":1,"../external":6,"../nodejs/NodejsStreamOutputAdapter":13,"../support":30,
"../utils":32,"./ConvertWorker":24,"./GenericWorker":28}],30:[function(e,t,n){"use strict";if(n.base64=!0,n.array=!0,n.string=!0,n.arraybuffer="undefined"!=typeof ArrayBuffer&&"undefined"!=typeof Uint8Array,n.nodebuffer="undefined"!=typeof Buffer,n.uint8array="undefined"!=typeof Uint8Array,"undefined"==typeof ArrayBuffer)n.blob=!1;else{var r=new ArrayBuffer(0);try{n.blob=0===new Blob([r],{type:"application/zip"}).size}catch(e){try{
var a=new(self.BlobBuilder||self.WebKitBlobBuilder||self.MozBlobBuilder||self.MSBlobBuilder);a.append(r),n.blob=0===a.getBlob("application/zip").size}catch(e){n.blob=!1}}}try{n.nodestream=!!e("readable-stream").Readable}catch(e){n.nodestream=!1}},{"readable-stream":16}],31:[function(e,t,n){"use strict";for(var r=e("./utils"),a=e("./support"),i=e("./nodejsUtils"),o=e("./stream/GenericWorker"),s=new Array(256),c=0;c<256;c++)s[c]=252<=c?6:248<=c?5:240<=c?4:224<=c?3:192<=c?2:1;function d(){
o.call(this,"utf-8 decode"),this.leftOver=null}function l(){o.call(this,"utf-8 encode")}s[254]=s[254]=1,n.utf8encode=function(e){return a.nodebuffer?i.newBufferFrom(e,"utf-8"):function(e){var t,n,r,i,o,s=e.length,c=0;for(i=0;i<s;i++)55296==(64512&(n=e.charCodeAt(i)))&&i+1<s&&56320==(64512&(r=e.charCodeAt(i+1)))&&(n=65536+(n-55296<<10)+(r-56320),i++),c+=n<128?1:n<2048?2:n<65536?3:4;for(t=a.uint8array?new Uint8Array(c):new Array(c),
i=o=0;o<c;i++)55296==(64512&(n=e.charCodeAt(i)))&&i+1<s&&56320==(64512&(r=e.charCodeAt(i+1)))&&(n=65536+(n-55296<<10)+(r-56320),i++),n<128?t[o++]=n:(n<2048?t[o++]=192|n>>>6:(n<65536?t[o++]=224|n>>>12:(t[o++]=240|n>>>18,t[o++]=128|n>>>12&63),t[o++]=128|n>>>6&63),t[o++]=128|63&n);return t}(e)},n.utf8decode=function(e){return a.nodebuffer?r.transformTo("nodebuffer",e).toString("utf-8"):function(e){var t,n,a,i,o=e.length,c=new Array(2*o)
;for(t=n=0;t<o;)if((a=e[t++])<128)c[n++]=a;else if(4<(i=s[a]))c[n++]=65533,t+=i-1;else{for(a&=2===i?31:3===i?15:7;1<i&&t<o;)a=a<<6|63&e[t++],i--;1<i?c[n++]=65533:a<65536?c[n++]=a:(a-=65536,c[n++]=55296|a>>10&1023,c[n++]=56320|1023&a)}return c.length!==n&&(c.subarray?c=c.subarray(0,n):c.length=n),r.applyFromCharCode(c)}(e=r.transformTo(a.uint8array?"uint8array":"array",e))},r.inherits(d,o),d.prototype.processChunk=function(e){var t=r.transformTo(a.uint8array?"uint8array":"array",e.data)
;if(this.leftOver&&this.leftOver.length){if(a.uint8array){var i=t;(t=new Uint8Array(i.length+this.leftOver.length)).set(this.leftOver,0),t.set(i,this.leftOver.length)}else t=this.leftOver.concat(t);this.leftOver=null}var o=function(e,t){var n;for((t=t||e.length)>e.length&&(t=e.length),n=t-1;0<=n&&128==(192&e[n]);)n--;return n<0||0===n?t:n+s[e[n]]>t?n:t}(t),c=t;o!==t.length&&(a.uint8array?(c=t.subarray(0,o),this.leftOver=t.subarray(o,t.length)):(c=t.slice(0,o),this.leftOver=t.slice(o,t.length))),
this.push({data:n.utf8decode(c),meta:e.meta})},d.prototype.flush=function(){this.leftOver&&this.leftOver.length&&(this.push({data:n.utf8decode(this.leftOver),meta:{}}),this.leftOver=null)},n.Utf8DecodeWorker=d,r.inherits(l,o),l.prototype.processChunk=function(e){this.push({data:n.utf8encode(e.data),meta:e.meta})},n.Utf8EncodeWorker=l},{"./nodejsUtils":14,"./stream/GenericWorker":28,"./support":30,"./utils":32}],32:[function(e,t,n){"use strict"
;var r=e("./support"),a=e("./base64"),i=e("./nodejsUtils"),o=e("./external");function s(e){return e}function c(e,t){for(var n=0;n<e.length;++n)t[n]=255&e.charCodeAt(n);return t}e("setimmediate"),n.newBlob=function(e,t){n.checkSupport("blob");try{return new Blob([e],{type:t})}catch(n){try{var r=new(self.BlobBuilder||self.WebKitBlobBuilder||self.MozBlobBuilder||self.MSBlobBuilder);return r.append(e),r.getBlob(t)}catch(e){throw new Error("Bug : can't construct the Blob.")}}};var d={
stringifyByChunk:function(e,t,n){var r=[],a=0,i=e.length;if(i<=n)retur…75034 tokens truncated…ype:b.settings.downloadType,downHeaders:s.Po.downHeaders,batchDelay:s.Po.batchDelay,directFlow:b.settings.directFlow,directRemoteDownload:Boolean(s.Po.directRemoteDownload),heavyCanvasExport:Boolean(s.Po.heavyCanvasExport)}]),b.optionsOpen=!1,
nn("ten-options").classList.remove("is-open")):Jt("请输入漫画名和章节名")}async function be(e){s.Po&&void 0!==s.Po.batchDelay&&e.forEach(e=>{void 0===e.batchDelay&&(e.batchDelay=s.Po.batchDelay)}),e.forEach(e=>{void 0===e.directFlow&&(e.directFlow=b.settings.directFlow),void 0===e.directRemoteDownload&&(e.directRemoteDownload=Boolean(s.Po&&s.Po.directRemoteDownload)),void 0===e.heavyCanvasExport&&(e.heavyCanvasExport=Boolean(s.Po&&s.Po.heavyCanvasExport))}),"function"!=typeof window.showDirectoryPicker||await(0,n.Oh)()||Jt("未选择保存目录，将使用浏览器默认下载目录"),e.forEach(e=>{e.useDirectory=Boolean(window.__tenComicDirectoryHandle||window.__ylDirectoryHandle)}),b.queue||(b.queue=new o(b.settings.maxChapters,b.settings.concurrentImages,b.settings.digits,{getHistoryData:Ae,$forceUpdate:Se,persistTasks:ke,notifyTask:en})),b.queue,b.queue.addList(e),b.queue.run(),F("tasks"),Ae()}function fe(e){if(e&&e.originHost)return String(e.originHost).toLowerCase();try{
return new URL(e&&e.url||"",window.location.href).hostname.toLowerCase()}catch(e){return window.location.hostname.toLowerCase()}}function xe(e){const t=new Set;return e.filter(e=>{if(!e||!e.url)return!1;const n=JSON.stringify([fe(e),e.comicName||"",e.downChapterName||e.chapterName||"",e.url]);return!t.has(n)&&(t.add(n),!0)})}function ve(){b.ready&&(nn("ten-recovery").hidden=0===b.recoveryTasks.length,
nn("ten-recovery-count").textContent=b.recoveryTasks.length?`${b.recoveryTasks.length} 个任务可恢复`:"")}async function ye(){const e=b.recoveryTasks.slice();e.length&&(b.recoveryTasks=[],ve(),await be(e),Jt(`已恢复 ${e.length} 个任务`))}async function we(){b.recoveryTasks.length&&await nt("放弃未完成任务",`将删除当前站点的 ${b.recoveryTasks.length} 个恢复点。`,"放弃任务")&&(b.recoveryTasks=[],_e(),ve(),Jt("未完成任务已放弃"))}function ke(){clearTimeout(b.persistTimer),b.persistTimer=setTimeout(_e,750)}function _e(){
clearTimeout(b.persistTimer),b.persistTimer=null;const e=window.location.hostname.toLowerCase(),t=v(u,[]),n=(Array.isArray(t)?t:[]).filter(t=>fe(t)!==e),a=b.queue?b.queue.pendingTasks():b.recoveryTasks;(0,r.po)(u,xe(n.concat(a)))}function Ee(){(b.queue||b.recoveryTasks.length)&&_e()}!function(){try{(0,r.Iq)()}catch(e){console.warn("10漫画：初始化存储失败。",e)}(0,s.HL)(window.location.href),s.Po?(b.settings=f(),window.addEventListener("keydown",w,{capture:!0,passive:!1}),
window.addEventListener("pageshow",k),window.addEventListener("pagehide",Ee),document.addEventListener("visibilitychange",St),function(){try{GM_registerMenuCommand("显示/隐藏 10漫画入口",R,{accessKey:"v",autoClose:!0}),GM_registerMenuCommand("重置 10漫画设置",Vt)}catch(e){console.warn("10漫画：菜单注册失败。",e)}}(),"loading"===document.readyState?document.addEventListener("DOMContentLoaded",k,{once:!0}):k()):function(){try{GM_registerMenuCommand("为当前网站添加自定义规则",y)}catch(e){console.warn("10漫画：自定义规则菜单注册失败。",e)}}()}()
;let Ce=null;function Se(){b.visible&&"tasks"!==b.activeTab||Ce||(Ce=requestAnimationFrame(()=>{Ce=null,Ae()}))}function Ae(){if(!b.ready)return;const e=b.queue?b.queue.worker.map((e,t)=>e?{item:e,index:t}:null).filter(Boolean):[],t=b.queue?b.queue.list.map((e,t)=>({item:e,index:t})).reverse():[];Ie(e,t.length),b.visible&&"tasks"===b.activeTab&&(rn(nn("ten-active-count"),e.length),rn(nn("ten-waiting-count"),t.length),function(e,t){
const n=nn("ten-toggle-all-active"),r=e.map(e=>e.item).filter(e=>!e.cancelled&&"cancelling"!==e.status),a=r.length>0&&r.every(e=>e.paused||"paused"===e.status);n.hidden=0===r.length,nn("ten-cancel-all-active").hidden=0===r.length;const i=a?"resume":"pause";n.dataset.bulkAction!==i&&(n.dataset.bulkAction=i),rn(n,a?"全部继续":"全部暂停"),nn("ten-remove-all-waiting").hidden=0===t}(e,t.length),function(e){const t=nn("ten-active-tasks");if(!e.length)return void Oe("ten-active-tasks",[],tn("当前没有下载任务"))
;delete t.dataset.renderKey;const n=new Set(e.map(e=>String(e.index)));cn("[data-worker-card]",t).forEach(e=>{n.has(e.dataset.workerCard)||e.remove()}),sn(".ten-empty",t)?.remove(),e.forEach(({item:e,index:n},r)=>{let a=sn(`[data-worker-card="${n}"]`,t);if(!a||a._tenTask!==e){const r=document.createElement("template");r.innerHTML=Ye(e,"active",n);const i=r.content.firstElementChild;a?a.replaceWith(i):t.appendChild(i),a=i,a._tenTask=e,a._tenNodes=Me(a)}!function(e,t){
const n=e._tenNodes||(e._tenNodes=Me(e)),r=Math.max(0,Math.min(100,Number(t.progress||0)));rn(n.title,t.downChapterName||t.chapterName||"未命名章节");const a=n.progress;on(a,"width",`${r}%`),on(a,"--ten-energy-duration",`${Fe(t.speedBps)}s`),a.classList.toggle("is-paused",Boolean(t.paused)),rn(n.stage,t.stage||"正在下载"),rn(n.stats,`${t.successNum||0}/${t.totalNumber||"?"} · ${r}%`),rn(n.speed,t.paused?"已暂停":$e(t.speedBps)),rn(n.eta,t.paused?"剩余 --":Ue(t.etaSeconds))
;const i=t.status||(t.paused?"paused":"running"),o=e.dataset.taskStatus;!o||o===i||"paused"!==i&&"running"!==i||Re(e,"paused"===i?"pause":"resume"),e.dataset.taskStatus!==i&&(e.dataset.taskStatus=i);const s=n.toggle,c="paused"===t.status,d=c?"resume":"pause";s.dataset.taskAction!==d&&(s.dataset.taskAction=d,s.title=c?"继续":"暂停",s.innerHTML=_(c?"play":"pause"))}(a,e);const i=t.children[r];i!==a&&t.insertBefore(a,i||null)})}(e),
Oe("ten-waiting-tasks",t.map(({item:e})=>[e.url,e.comicName,e.downChapterName]),()=>t.length?t.map(({item:e,index:n},r)=>Ye(e,"waiting",n,r,t.length)).join(""):tn("等待队列为空")),function(){const e=Xe(),t=`${b.historyFilter}|${b.historyRaw}`;if(t===b.historyRenderKey)return;b.historyRenderKey=t;const n=function(e){
return"completed"===b.historyFilter?e.filter(e=>"completed"===e.status||!e.status&&!e.hasError):"failed"===b.historyFilter?e.filter(e=>"failed"===e.status||"partial"===e.status||e.hasError):"cancelled"===b.historyFilter?e.filter(e=>"cancelled"===e.status):e}(e);rn(nn("ten-history-count"),e.length),Oe("ten-history",[b.historyFilter,...n.map(e=>[e.id,e.status,e.comicName,e.downChapterName,e.failedImages?.length])],n.length?n.map(Ke).join(""):tn(e.length?"没有符合筛选条件的记录":"暂无下载记录")),
cn("[data-history-filter]").forEach(e=>{const t=e.dataset.historyFilter===b.historyFilter;e.classList.toggle("is-active",t),an(e,"aria-pressed",String(t))}),function(e){const t=e[0],n=t&&Number(t.id)||0;if(null!==b.lastHistoryId){if(n>b.lastHistoryId&&"cancelled"!==t.status){const e="completed"===t.status||!t.status&&!t.hasError;Re(sn('[data-task-group="history"]'),e?"success":"danger")}b.lastHistoryId=n}else b.lastHistoryId=n}(e)}(),je("active",e.length),je("waiting",t.length))}
function Ie(e,t){if(!b.ready&&!nn("ten-mini-task"))return;const n=(b.miniNodes?.root?.isConnected||(b.miniNodes={root:nn("ten-mini-task"),launcher:nn(l),title:nn("ten-mini-title"),meta:nn("ten-mini-meta"),progress:nn("ten-mini-progress"),toggle:nn("ten-mini-toggle")}),
b.miniNodes),r=Array.isArray(e)?e.map(e=>e.item):b.queue?b.queue.worker.filter(Boolean):[],a=r.filter(e=>!e.cancelled&&"cancelling"!==e.status),i=Number.isFinite(t)?t:b.queue?b.queue.list.length:0,o=n.root,s=Boolean((r.length||i)&&!b.visible&&!b.rulePicking);if(o.classList.toggle("is-hidden",!s),o.setAttribute("aria-hidden",String(!s)),s?n.launcher.classList.add("is-hidden"):n.launcher.classList.toggle("is-hidden",b.visible||!b.launcherVisible),!s)return
;const c=a.length>0&&a.every(e=>e.paused||"paused"===e.status),d=a.reduce((e,t)=>e+(Number(t.speedBps)||0),0),u=a.reduce((e,t)=>Math.max(e,Number(t.etaSeconds)||0),0),p=r.filter(e=>Number(e.totalNumber)>0),h=p.length?p.reduce((e,t)=>e+Math.min(Number(t.successNum)||0,Number(t.totalNumber)),0)/p.reduce((e,t)=>e+Number(t.totalNumber),0)*100:r.length?r.reduce((e,t)=>e+(Number(t.progress)||0),0)/r.length:0;rn(n.title,r.length?c?`${r.length} 个章节已暂停`:`${r.length} 个章节下载中`:`${i} 个章节等待`),
rn(n.meta,r.length?c?(i?`${i} 个等待 · `:"")+"点击继续":`${$e(d)} · ${Ue(u)}`:"打开任务页查看队列"),on(n.progress,"width",`${Math.max(0,Math.min(100,h))}%`);const m=n.toggle;m.hidden=0===a.length;const g=c?"resume":"pause",f=c?"全部继续":"全部暂停";an(m,"aria-label",f),m.dataset.action!==g&&(m.dataset.action=g,m.title=f,m.innerHTML=_(c?"play":"pause"))}function Ne(){if(!b.queue)return;const e=b.queue.worker.filter(e=>e&&!e.cancelled&&"cancelling"!==e.status);if(!e.length)return
;const t=e.every(e=>e.paused||"paused"===e.status),n=b.queue.setAllPaused(!t);n&&Jt(t?`已继续 ${n} 个任务`:`已暂停 ${n} 个任务`),Ae()}function Le(e){return e instanceof Element?e.closest(".ten-icon-btn, .ten-task-arrow-button, .ten-mini-toggle, .ten-number-steps button"):null}function Te(e){const t=Le(e.target);t&&t!==b.iconTipTarget&&(clearTimeout(b.iconTipTimer),b.iconTipTimer=setTimeout(()=>ze({target:t}),320))}function ze(e){const t=Le(e.target);if(!t)return;const n=t.getAttribute("title")
;n&&(t.dataset.tenTip=n,t.removeAttribute("title"));const r=t.dataset.tenTip||t.getAttribute("aria-label");if(!r)return;clearTimeout(b.iconTipTimer),Be(),b.iconTipTarget=t,t.setAttribute("aria-describedby","ten-icon-tooltip");const a=nn("ten-icon-tooltip");a.textContent=r,a.classList.add("is-show"),a.setAttribute("aria-hidden","false"),requestAnimationFrame(()=>function(e,t){if(e!==b.iconTipTarget||!e.isConnected)return
;const n=e.getBoundingClientRect(),r=t.getBoundingClientRect(),a=Math.max(8,Math.min(window.innerWidth-r.width-8,n.left+n.width/2-r.width/2)),i=n.top-r.height-8;t.style.left=`${a}px`,t.style.top=`${i>=8?i:n.bottom+8}px`}(t,a))}function De(e){const t=Le(e.target);t&&e.relatedTarget instanceof Node&&t.contains(e.relatedTarget)||(clearTimeout(b.iconTipTimer),b.iconTipTimer=null,t&&t!==b.iconTipTarget||Be())}function Be(){clearTimeout(b.iconTipTimer),b.iconTipTimer=null,
b.iconTipTarget&&b.iconTipTarget.removeAttribute("aria-describedby"),b.iconTipTarget=null;const e=nn("ten-icon-tooltip");e&&(e.classList.remove("is-show"),e.setAttribute("aria-hidden","true"))}function Pe(e){const t=e.closest(".ten-task-group");if(!t)return;const n=t.classList.toggle("is-open");sn(".ten-task-title-button",t)?.setAttribute("aria-expanded",String(n)),sn(".ten-task-arrow-button",t)?.setAttribute("aria-expanded",String(n))}function Oe(e,t,n){const r=nn(e),a=JSON.stringify(t)
;r.dataset.renderKey!==a&&(r.innerHTML="function"==typeof n?n():n,r.dataset.renderKey=a)}function Me(e){return{title:sn("[data-task-title]",e),progress:sn("[data-task-progress]",e),stage:sn("[data-task-stage]",e),stats:sn("[data-task-stats]",e),speed:sn("[data-task-speed]",e),eta:sn("[data-task-eta]",e),toggle:sn("[data-task-toggle]",e)}}function Re(e,t){e&&0!==b.settings.effectLevel&&(clearTimeout(e._tenStateTimer),
e.classList.remove("ten-state-animate","is-state-pause","is-state-resume","is-state-success","is-state-danger"),e.offsetWidth,e.classList.add("ten-state-animate",`is-state-${t}`),e._tenStateTimer=setTimeout(()=>{e.classList.remove("ten-state-animate",`is-state-${t}`)},2===b.settings.effectLevel?800:1e3))}function $e(e){const t=Number(e)||0;return t<=0?"速度计算中":t<1024?`${Math.round(t)} B/s`:t<1048576?`${(t/1024).toFixed(1)} KB/s`:`${(t/1024/1024).toFixed(1)} MB/s`}function Fe(e){
const t=Math.max(0,Number(e)||0),n=Math.log2(1+t/32768);let r=Math.max(1.6,Math.min(6.6,6.6-.75*n));return 1===b.settings.effectLevel&&(r*=1.2),r.toFixed(2)}function formatDurationValue(e){const t=Number(e);if(!Number.isFinite(t)||t<0)return"";const n=Math.max(0,Math.round(t/1e3));return n<60?`${n}秒`:n<3600?`${Math.floor(n/60)}分${n%60}秒`:`${Math.floor(n/3600)}时${Math.floor(n%3600/60)}分`}function formatCompletedAt(e){if(!e)return"";const t=new Date(e);return Number.isNaN(t.getTime())?"":`完成 ${t.toLocaleString()}`}function formatHistoryTiming(e){const t=[formatTaskDuration(e.durationMs)],n=formatDurationValue(e.totalDurationMs),r=formatDurationValue(e.pausedDurationMs),a=formatCompletedAt(e.completedAt);return n&&t.push(`总历时 ${n}`),Number.isFinite(Number(e.pausedDurationMs))&&r&&t.push(`暂停 ${r}`),a&&t.push(a),t.join(" · ")}function formatTaskDuration(e){const t=formatDurationValue(e);return t?`用时 ${t}`:"用时未记录"}function Ue(e){if(!Number.isFinite(e))return"剩余时间估算中";const t=Math.max(0,Math.round(e));return t<=1?"即将完成":t<60?`剩余 ${t} 秒`:t<3600?`剩余 ${Math.floor(t/60)}分${t%60}秒`:`剩余 ${Math.floor(t/3600)}时${Math.ceil(t%3600/60)}分`}function je(e,t){const n=sn(`[data-task-group="${e}"]`);if(!n)return;n.classList.toggle("has-scroll",t>5),
t>0&&"true"!==n.dataset.seen&&(n.dataset.seen="true",n.classList.add("is-open")),0===t&&(delete n.dataset.seen,"waiting"!==e&&n.classList.remove("is-open"));const r=String(n.classList.contains("is-open"));an(sn(".ten-task-title-button",n),"aria-expanded",r),an(sn(".ten-task-arrow-button",n),"aria-expanded",r)}function We(e){if(!b.queue)return;const t="resume"!==e.currentTarget.dataset.bulkAction,n=b.queue.setAllPaused(t);n&&Jt(t?`已暂停 ${n} 个任务`:`已继续 ${n} 个任务`),Ae()}async function He(){
if(!b.queue)return;const e=b.queue.worker.filter(e=>e&&!e.cancelled).length;if(!e||!await nt("取消全部下载任务",`确认取消当前正在进行的 ${e} 个任务？`,"全部取消"))return;const t=b.queue.cancelAll();Ae(),t&&Jt(`正在取消 ${t} 个任务`)}async function qe(){if(!b.queue||!b.queue.list.length)return;const e=b.queue.list.length;if(!await nt("移出全部等待任务",`确认将等待队列中的 ${e} 个任务全部移出？`,"全部移出"))return;const t=b.queue.list.slice(),n=b.queue.clearWaiting();Ae(),n&&Jt(`已移出 ${n} 个等待任务`,()=>Ze(t))}function Ze(e){
b.queue&&e.length&&(b.queue.list.push(...e),b.queue.run(),Ae())}function Ye(e,t,n,r=0,a=0){
const i=Math.max(0,Math.min(100,Number(e.progress||0))),o="active"===t,s="paused"===e.status,c=o?`<div class="ten-task-actions"><button class="ten-icon-btn" type="button" data-task-toggle data-task-action="${s?"resume":"pause"}" data-worker-index="${n}" title="${s?"继续":"暂停"}">${_(s?"play":"pause")}</button><button class="ten-icon-btn" type="button" data-task-action="diagnostic" data-worker-index="${n}" title="诊断信息">${_("info")}</button><button class="ten-icon-btn is-danger" type="button" data-task-action="cancel" data-worker-index="${n}" title="取消任务">${_("close")}</button></div>`:`<div class="ten-task-actions"><button class="ten-icon-btn" type="button" data-task-action="waiting-up" data-waiting-index="${n}" title="提前一个位置" ${0===r?"disabled":""}>${_("up")}</button><button class="ten-icon-btn" type="button" data-task-action="waiting-down" data-waiting-index="${n}" title="延后一个位置" ${r===a-1?"disabled":""}>${_("down")}</button><button class="ten-icon-btn is-danger" type="button" data-task-action="cancel-waiting" data-waiting-index="${n}" title="移出队列">${_("close")}</button></div>`
;return`<div class="ten-list-item ten-task-card"${o?` data-worker-card="${n}"`:""}><div class="ten-name"><div class="ten-task-title"${o?" data-task-title":""}>${dn(e.downChapterName||e.chapterName||"未命名章节")}</div>${o?`<div class="ten-progress"><i data-task-progress${e.paused?' class="is-paused"':""} style="width:${i}%;--ten-energy-duration:${Fe(e.speedBps)}s"></i></div><div class="ten-task-meta"><span data-task-stage>${dn(e.stage||"正在下载")}</span><span data-task-stats>${e.successNum||0}/${e.totalNumber||"?"} · ${i}%</span></div><div class="ten-task-performance"><span data-task-speed>${$e(e.speedBps)}</span><span data-task-eta>${Ue(e.etaSeconds)}</span></div>`:'<div class="ten-meta">等待开始</div>'}</div>${c}</div>`
}function Ke(e){const t={completed:"已完成",partial:"部分失败",failed:"失败",cancelled:"已取消"}[e.status]||(e.hasError?"存在错误":"已完成"),n=Array.isArray(e.failedImages)?e.failedImages.filter(e=>e&&e.url):[]
;return`<div class="ten-list-item ten-history-card"><div class="ten-name"><div class="ten-task-title">${dn(e.downChapterName||"未命名章节")}</div><div class="ten-task-meta"><span>${formatHistoryTiming(e)}</span><span>${dn(e.flowUsed||"流程未记录")}</span><span class="ten-task-state is-${ln(e.status||(e.hasError?"failed":"completed"))}">${t}</span></div></div><div class="ten-task-actions">${n.length?`<button class="ten-icon-btn" type="button" data-retry-history="${e.id}" title="仅重试 ${n.length} 张失败图片">${_("refresh")}</button><button class="ten-icon-btn" type="button" data-copy-failures="${e.id}" title="复制失败清单">${_("copy")}</button>`:""}<button class="ten-icon-btn" type="button" data-diagnostic-history="${e.id}" title="诊断信息">${_("info")}</button><button class="ten-icon-btn" type="button" data-delete-history="${e.id}" title="删除记录">${_("trash")}</button></div></div>`
}function Ve(e){const t=e.target.closest("[data-history-filter]");t&&t.dataset.historyFilter!==b.historyFilter&&(b.historyFilter=t.dataset.historyFilter,Ae())}async function Ge(e){const t=e.target.closest("[data-task-action]");if(!t||!b.queue)return;const n=t.dataset.taskAction;if("waiting-up"===n||"waiting-down"===n)return b.queue.moveWaiting(Number(t.dataset.waitingIndex),"waiting-up"===n?"up":"down"),Ae();if("cancel-waiting"===n){const e=Number(t.dataset.waitingIndex),n=b.queue.list[e]
;return b.queue.cancelWaiting(e)&&Jt("任务已移出等待队列",()=>Ze([n])),Ae()}const r=Number(t.dataset.workerIndex),a=b.queue.worker[r];a&&("pause"===n&&b.queue.pause(r),"resume"===n&&b.queue.resume(r),"diagnostic"===n&&ot(a),"cancel"===n&&await nt("取消下载任务",`确认取消“${a.comicName} · ${a.downChapterName}”？`,"取消任务")&&b.queue.cancel(r),Ae())}function Xe(){const e=localStorage.getItem("ylComicDownHistory")||"[]";if(e===b.historyRaw)return b.historyCache;try{const t=JSON.parse(e);if(!Array.isArray(t))return Je([])
;let n=!1;const r=100*Date.now();t.forEach((e,t)=>{e&&void 0===e.id&&(e.id=r-t,n=!0)});const a=new Set,i=t.filter(e=>{const t=`${e.comicName||""}\0${e.downChapterName||""}`;return!a.has(t)&&(a.add(t),!0)}).slice(0,b.settings?b.settings.historyLimit:x(v("historyLimit",100),100,10,500)),o=n||i.length!==t.length?JSON.stringify(i):e;return o!==e&&localStorage.setItem("ylComicDownHistory",o),b.historyRaw=o,b.historyCache=i,i}catch(t){return b.historyRaw=e,b.historyCache=[],b.historyCache}}
function Je(e){const t=Array.isArray(e)?e:[],n=JSON.stringify(t);return localStorage.setItem("ylComicDownHistory",n),b.historyRaw=n,b.historyCache=t,b.historyRenderKey="",t}async function Qe(e){const t=e.target.closest("[data-diagnostic-history]"),n=e.target.closest("[data-retry-history]"),r=e.target.closest("[data-copy-failures]"),a=e.target.closest("[data-delete-history]"),i=Xe();if(t)return ot(i.find(e=>String(e.id)===t.dataset.diagnosticHistory));if(n)return function(e){
const t=Array.isArray(e&&e.failedImages)?e.failedImages.filter(e=>e&&e.url):[];if(!t.length)return Jt("没有可重试的失败图片");const n=e.task&&"object"==typeof e.task?e.task:{};be([{...n,comicName:e.comicName,chapterName:e.downChapterName,downChapterName:e.downChapterName,url:n.url||e.comicPageUrl,readtype:void 0===n.readtype?1:n.readtype,downType:0,retryImages:t}]),Jt(`已加入 ${t.length} 张失败图片`)}(i.find(e=>String(e.id)===n.dataset.retryHistory))
;if(r)return dt(i.find(e=>String(e.id)===r.dataset.copyFailures));if(!a)return;const o=i.findIndex(e=>String(e.id)===a.dataset.deleteHistory),s=i[o];s&&await nt("删除下载记录",`确认删除“${s.comicName||"未命名漫画"} · ${s.downChapterName||"未命名章节"}”？`,"删除")&&(i.splice(o,1),Je(i),Ae(),Jt("下载记录已删除",()=>function(e,t){if(!e)return;const n=Xe().slice();n.some(t=>String(t.id)===String(e.id))||(n.splice(Math.max(0,Math.min(t,n.length)),0,e),Je(n),Ae())}(s,o)))}function et(){Je(Xe().slice(0,b.settings.historyLimit)),
Ae()}async function tt(){const e=Xe();if(!e.length)return Jt("当前没有下载记录");await nt("清空下载记录",`将删除全部 ${e.length} 条下载记录，此操作无法撤销。`,"全部清空")&&(Je([]),Ae(),Jt("下载记录已清空"))}function nt(e,t,n="确认"){b.confirmResolve&&rt(!1),nn("ten-confirm-title").textContent=e,nn("ten-confirm-message").textContent=t,nn("ten-confirm-ok").textContent=n;const r=nn("ten-confirm");return r.classList.add("is-open"),r.setAttribute("aria-hidden","false"),setTimeout(()=>nn("ten-confirm-cancel").focus(),0),new Promise(e=>{
b.confirmResolve=e})}function rt(e){const t=b.confirmResolve;b.confirmResolve=null;const n=nn("ten-confirm");n&&(n.classList.remove("is-open"),n.setAttribute("aria-hidden","true")),t&&t(e)}function at(){const e=nn("ten-rule-guide");e&&(e.classList.add("is-open"),e.setAttribute("aria-hidden","false"),setTimeout(()=>e.querySelector(".ten-rule-guide-dialog [data-rule-guide-close]")?.focus(),0))}function it(){const e=nn("ten-rule-guide");e&&(e.classList.remove("is-open"),
e.setAttribute("aria-hidden","true"))}function ot(e){if(!e)return;b.diagnosticItem=e;const t=Array.isArray(e.diagnostics)?e.diagnostics:[],n=Array.isArray(e.failedImages)?e.failedImages:Array.isArray(e.failures)?e.failures:[],r=e.stage||(e.hasError?"存在下载错误":"没有发现错误"),a=[`漫画：${e.comicName||"未知"}`,`章节：${e.downChapterName||e.chapterName||"未知"}`,`状态：${r}`,`页面：${e.comicPageUrl||e.url||window.location.href}`,`失败图片：${n.length} 张`,""];t.length?(a.push("诊断详情："),t.forEach((e,t)=>{
const n=e.time?new Date(e.time).toLocaleString():"未知时间";a.push(`${t+1}. [${n}] ${e.stage||"下载"}：${e.message||"未知错误"}`),e.imgIndex&&a.push(`   图片序号：${e.imgIndex}`),e.url&&a.push(`   地址：${e.url}`)})):a.push(e.hasError?"这是旧版记录，没有保存详细错误信息。":"当前没有错误详情。"),nn("ten-diagnostic-summary").textContent=`${e.comicName||"未知漫画"} · ${e.downChapterName||e.chapterName||"未知章节"}`,nn("ten-diagnostic-content").textContent=a.join("\n");const i=nn("ten-diagnostic");i.classList.add("is-open"),
i.setAttribute("aria-hidden","false")}function st(){const e=nn("ten-diagnostic");e&&(e.classList.remove("is-open"),e.setAttribute("aria-hidden","true"))}function ct(){lt(nn("ten-diagnostic-content").textContent,"诊断信息已复制")}function dt(e){const t=Array.isArray(e&&e.failedImages)?e.failedImages:Array.isArray(e&&e.failures)?e.failures:[];if(!t.length)return Jt("没有失败图片可复制");const n=[`漫画：${e.comicName||"未知"}`,`章节：${e.downChapterName||e.chapterName||"未知"}`,`失败图片：${t.length} 张`,""]
;t.forEach((e,t)=>n.push(`${t+1}. 序号：${e.imgIndex||"未知"}\n   原因：${e.reason||"未知错误"}\n   地址：${e.url||"无"}`)),lt(n.join("\n"),"失败清单已复制")}function lt(e,t){try{GM_setClipboard(e,"text"),Jt(t)}catch(n){navigator.clipboard&&"function"==typeof navigator.clipboard.writeText?navigator.clipboard.writeText(e).then(()=>Jt(t)).catch(()=>Jt("复制失败")):Jt("复制失败")}}function ut(e,t){const n=v("appLoadDefault",{}),a=n&&"object"==typeof n?n:{};a[e]=t,(0,r.po)("appLoadDefault",a),
"isShowUI"===e&&(b.settings.autoOpen=t)}function pt(e,t){b.settings.scale=e,nn(d).style.setProperty("--ten-scale",e/100),nn("ten-scale-value").textContent=`${e}%`,t&&ut("rightSize",e)}function ht(e,t){const n=Math.max(0,Math.min(2,Number(e)||0));b.settings.effectLevel=n,nn(c).dataset.effects=String(n),Gt(n),cn("[data-effect-level]").forEach(e=>{const t=Number(e.dataset.effectLevel)===n;e.classList.toggle("is-active",t),e.setAttribute("aria-pressed",String(t))}),t&&((0,r.po)("effectLevel",n),
Jt(["特效已关闭","已切换为轻量特效","已切换为标准特效"][n]))}function mt(e,t){const n=Object.prototype.hasOwnProperty.call(h,e)?e:"glass";b.settings.themePreset=n,nn(c).dataset.theme=n,cn("[data-theme-choice]").forEach(e=>e.setAttribute("aria-pressed",String(e.dataset.themeChoice===n))),t&&((0,r.po)("themePreset",n),Jt(`已切换为${h[n][0]}`))}function gt(e){const t=nn(c),n=e||{};t.dataset.density=n.density||"standard",t.dataset.shape=n.shape||"standard",t.dataset.motion=n.motion||"standard",
cn("[data-appearance-axis]").forEach(e=>{const t=e.dataset.appearanceValue===n[e.dataset.appearanceAxis];e.classList.toggle("is-active",t),an(e,"aria-pressed",String(t))})}function bt(){const e=Math.max(1,Math.trunc(Number(nn("ten-range-start").value)||1)),t=Math.trunc(Number(nn("ten-range-end").value)||-1),n=-1===t?-1:Math.max(e,t);b.settings.imageRange=[e,n],nn("ten-range-start").value=e,nn("ten-range-end").value=n,(0,r.po)("imgDownRange",b.settings.imageRange)}function ft(){
const e=Object.fromEntries(p.map(e=>[e,v(e,null)])),n={format:"10Comic-settings-backup",version:1,exportedAt:(new Date).toISOString(),settings:e,rules:Array.isArray(v("userWebInfo",[]))?v("userWebInfo",[]):[]},r=(new Date).toISOString().slice(0,10);!function(e,t){const n=URL.createObjectURL(e);let r=!1,a=!1;const i=()=>{r||(r=!0,URL.revokeObjectURL(n))},o=()=>{if(r||a)return
;a=!0;const e=document.createElement("a");e.href=n,e.download=t,e.hidden=!0,document.body.appendChild(e),e.click(),e.remove(),setTimeout(i,1e3),Jt("设置与规则备份已导出")};try{GM_download({url:n,name:t,saveAs:!0,onload:()=>{i(),Jt("设置与规则备份已导出")},onerror:o,ontimeout:o})}catch(e){o()}}(new Blob([JSON.stringify(n,null,2)],{type:"application/json"}),`10Comic-设置与规则备份-${r}.json`)}async function xt(e){const t=e.target.files&&e.target.files[0];if(e.target.value="",t)try{const e=JSON.parse(await t.text())
;if(!e||"10Comic-settings-backup"!==e.format||!e.settings||!Array.isArray(e.rules))throw new Error("不是有效的 10漫画备份文件");const n=e=>(Array.isArray(e)?e:[e]).some(e=>String(e||"").trim());if(e.rules.some(e=>!e||!n(e.domain)))throw new Error("备份中的规则域名无效");if(!await nt("导入设置与规则",`将使用备份中的设置和 ${e.rules.length} 条规则覆盖当前配置。`,"确认导入"))return;p.forEach(t=>{void 0!==e.settings[t]&&null!==e.settings[t]&&(0,r.po)(t,e.settings[t])}),(0,r.po)("userWebInfo",e.rules),b.settings=f(),P(),et(),U(),Jt(`备份已导入，共 ${e.rules.length} 条规则`)}catch(e){Jt(e.message||"备份文件读取失败")}}function vt(){let e=document.getElementById("ten-comic-page-style");e||(e=document.createElement("style"),
e.id="ten-comic-page-style",document.head.appendChild(e)),e.textContent=b.settings.splicePage&&s.Po&&s.Po.readCssText?s.Po.readCssText:""}async function yt(){if("function"==typeof window.showDirectoryPicker)try{const e=await(0,n.IJ)();e&&(b.dirHandle=e,nn("ten-dir-name").textContent=e.name,Jt("保存目录已更新"))}catch(e){e&&"AbortError"!==e.name&&Jt("目录选择失败")}else Jt("当前浏览器将使用默认下载目录")}function St(){document.hidden||b.queue&&b.queue.refresh()}const It={title:{field:"ten-rule-title-selector",label:"漫画标题",role:"title"},chapters:{field:"ten-rule-chapter-selector",label:"章节列表",role:"chapters"},images:{field:"ten-rule-image-selector",label:"章节图片",role:"images"}},Nt={basic:{name:"基础卷轴",
imageCss:".reader img, .viewer img, .comic-content img",readtype:1,useFrame:!1},lazy:{name:"懒加载阅读",imageCss:"img[data-src], img[data-original], img[data-url], img[data-lazy-src]",readtype:1,useFrame:!1},frame:{name:"隐藏页面",imageCss:".reader img, .viewer img, .comic-content img",readtype:1,useFrame:!0},paged:{name:"翻页阅读",imageCss:"",readtype:0,useFrame:!1}};function Lt(e){if(!b.rulePicking||nn(c).contains(e.target))return;const t=Ot(e.target,b.rulePicking.role)
;t&&t!==b.rulePickElement&&(b.rulePickElement=t,cancelAnimationFrame(b.rulePickFrame),b.rulePickFrame=requestAnimationFrame(Tt))}function Tt(){if(!b.rulePicking||!b.rulePickElement?.isConnected)return;const e=b.rulePickElement.getBoundingClientRect();nn("ten-rule-pick-box").style.cssText=`left:${e.left}px;top:${e.top}px;width:${e.width}px;height:${e.height}px`,nn("ten-rule-pick-selector").textContent=Mt(b.rulePickElement,b.rulePicking.role)||"无法生成选择器，请选择其他元素"}function zt(e){
if(!b.rulePicking||nn(c).contains(e.target))return;e.preventDefault(),e.stopImmediatePropagation();const t=Mt(Ot(e.target,b.rulePicking.role),b.rulePicking.role);if(!t)return;const n=b.rulePicking;Pt();const r=nn(n.field);r.value=t,r.dispatchEvent(new Event("input",{bubbles:!0})),nn("ten-rule-editor-card").scrollIntoView({behavior:"smooth",block:"start"}),setTimeout(()=>r.focus(),260),Jt(`已选择${n.label}：${t}`)}function Dt(e){"Escape"===e.key&&(e.preventDefault(),e.stopImmediatePropagation(),Bt())
}function Bt(){b.rulePicking&&(Pt(),Jt("已取消可视化选择"))}function Pt(){cancelAnimationFrame(b.rulePickFrame),b.rulePickFrame=null,b.rulePicking=null,b.rulePickElement=null,document.removeEventListener("pointermove",Lt,!0),document.removeEventListener("click",zt,!0),document.removeEventListener("keydown",Dt,!0),window.removeEventListener("scroll",Tt,!0),window.removeEventListener("resize",Tt,!0),nn(c).classList.remove("is-rule-picking"),
document.documentElement.classList.remove("ten-rule-picking-page");const e=nn("ten-rule-pick-layer");e.classList.add("is-hidden"),e.setAttribute("aria-hidden","true"),nn("ten-rule-pick-box").removeAttribute("style"),Ie()}function Ot(e,t){if(!(e instanceof Element))return null;if("images"===t)return e.closest("img")||e.querySelector("img")||e;if("chapters"!==t)return e;let n=e.closest("a")||e;n.matches("a")&&(n=n.parentElement);for(let e=0;n&&e<5;e++,
n=n.parentElement)if(n.querySelectorAll("a[href]").length>1)return n;return e}function Mt(e,t){if(!e)return"";if("images"===t&&e.matches("img")){const t=$t(e);for(const e of t){const t=`img.${Ut(e)}`;if(Ft(t)>1)return t}let n=e.parentElement;for(let e=0;n&&e<5;e++,n=n.parentElement){if(n.querySelectorAll("img").length<2)continue;const e=Rt(n);if(e)return`${e} img`}}return Rt(e)}function Rt(e){if(!e||!e.tagName)return"";if(e.id){const t=`#${Ut(e.id)}`;if(1===Ft(t))return t}
const t=e.tagName.toLowerCase(),n=$t(e);for(let e=1;e<=Math.min(2,n.length);e++){const r=t+n.slice(0,e).map(e=>`.${Ut(e)}`).join("");if(1===Ft(r))return r}const r=[];let a=e;for(let e=0;a&&a!==document.documentElement&&e<6;e++,a=a.parentElement){let e=a.tagName.toLowerCase();const t=$t(a);t.length&&(e+=`.${Ut(t[0])}`);const n=a.parentElement?Array.from(a.parentElement.children).filter(e=>e.tagName===a.tagName):[];n.length>1&&(e+=`:nth-of-type(${n.indexOf(a)+1})`),r.unshift(e)
;const i=r.join(" > ");if(1===Ft(i))return i}return r.join(" > ")}function $t(e){return Array.from(e.classList||[]).filter(e=>e.length<=36&&!/\d{4,}|(^|[-_])(active|selected|current|hover|focus|open|loading|show|hide)([-_]|$)/i.test(e)).slice(0,3)}function Ft(e){try{return document.querySelectorAll(e).length}catch(e){return 0}}function Ut(e){return window.CSS&&"function"==typeof window.CSS.escape?window.CSS.escape(String(e)):String(e).replace(/[^a-zA-Z0-9_-]/g,e=>`\\${e}`)}function jt(e){
b.ruleReadType=0===Number(e)?0:1;const t=sn(".ten-rule-readtype");t&&t.style.setProperty("--rule-type",1===b.ruleReadType?0:1),cn("[data-rule-readtype]").forEach(e=>e.classList.toggle("is-active",Number(e.dataset.ruleReadtype)===b.ruleReadType))}function Wt(){b.editRuleIndex=-1,b.editRuleBase=null,b.ruleReadType=1,["ten-rule-name","ten-rule-domain","ten-rule-homepage","ten-rule-desc","ten-rule-title-selector","ten-rule-chapter-selector","ten-rule-image-selector","ten-rule-getimgs"].forEach(e=>{
nn(e)&&(nn(e).value="")}),nn("ten-rule-use-frame")&&(nn("ten-rule-use-frame").checked=!1),nn("ten-rule-advanced")&&(nn("ten-rule-advanced").open=!1),nn("ten-rule-save")&&(nn("ten-rule-save").textContent="保存规则"),nn("ten-rule-cancel-edit")&&(nn("ten-rule-cancel-edit").hidden=!0),nn("ten-rule-test-result")&&(nn("ten-rule-test-result").hidden=!0),jt(1)}function Ht(){
const e=nn("ten-rule-name").value.trim(),t=nn("ten-rule-domain").value.split(/[,，\s]+/).map(e=>e.trim().toLowerCase().replace(/^https?:\/\//,"").split("/")[0].replace(/^\*\./,"")).filter(Boolean),n=nn("ten-rule-homepage").value.trim()||(t[0]?`https://${t[0]}/`:""),r=nn("ten-rule-image-selector").value.trim(),a=nn("ten-rule-getimgs").value.trim(),i=Boolean(r&&!a),o=a||(r?(["function(context, processData) {\n    const frame = processData && processData.frameId ? document.getElementById(processData.frameId) : null\n    const root = frame && frame.contentDocument ? frame.contentDocument : new DOMParser().parseFromString(String(context || ''), 'text/html')\n    const base = processData && processData.url ? processData.url : location.h",
"ref\n    const urls = Array.from(root.querySelectorAll(this.imageCss)).map(img => {\n      const srcset = img.getAttribute('srcset') || img.getAttribute('data-srcset') || ''\n      return img.getAttribute('data-src') || img.getAttribute('data-original') || img.getAttribute('data-url') || img.getAttribute('data-lazy-src') || img.currentSrc || (srcset.trim().spli",
"t(/\\s*,\\s*/).pop() || '').trim().split(/\\s+/)[0] || img.getAttribute('src')\n    }).filter(Boolean).map(url => { try { return new URL(url, base).href } catch (error) { return url } })\n    if (frame) frame.remove()\n    return [...new Set(urls)]\n  }"].join(""))
:"")
;if(!e||!t.length)throw new Error("请填写站点名称和域名");if(!o)throw new Error("请填写章节图片选择器；复杂站点也可填写图片解析函数");if(i&&0===b.ruleReadType)throw new Error("翻页阅读需要在复杂站点设置中填写图片解析函数");try{new URL(n)}catch(e){throw new Error("站点首页地址格式不正确")}if(!/^(async\s+)?function\s*\(/.test(o))throw new Error("图片解析函数必须使用 function 或 async function 格式");let s;try{s=Function(`"use strict";return (${o})`)()}catch(e){throw new Error("图片解析函数存在语法错误")}if("function"!=typeof s)throw new Error("图片解析函数格式不正确");if(r)try{
document.querySelector(r)}catch(e){throw new Error("章节图片选择器格式不正确")}return{...b.editRuleBase||{},webName:e,domain:1===t.length?t[0]:t,homepage:n,webDesc:nn("ten-rule-desc").value.trim(),comicNameCss:nn("ten-rule-title-selector").value.trim(),chapterCss:nn("ten-rule-chapter-selector").value.trim(),readtype:b.ruleReadType,useFrame:nn("ten-rule-use-frame").checked,imageCss:r,simpleRule:i,getImgs:o}}function qt(){const e=nn("ten-rule-test-result");e.hidden=!1,
e.classList.remove("is-success","is-error");try{const t=Ht(),n=Array.isArray(t.domain)?t.domain:[t.domain],r=window.location.hostname.toLowerCase(),a=["规则格式：通过","域名匹配："+(n.some(e=>r===e.toLowerCase()||r.endsWith(`.${e.toLowerCase()}`))?"当前页面已匹配":"当前页面不属于该规则，仅检查格式")];if(t.comicNameCss){let e;try{e=document.querySelector(t.comicNameCss)}catch(e){throw new Error("漫画标题选择器格式不正确")}a.push(`漫画标题：${e?String(e.textContent||"").trim().slice(0,60)||"已找到节点":"未找到"}`)}if(t.chapterCss){let e;try{
e=[...document.querySelectorAll(t.chapterCss)]}catch(e){throw new Error("章节列表选择器格式不正确")}const n=e.reduce((e,t)=>e+t.querySelectorAll("a").length,0);a.push(`章节列表：${e.length} 个容器，${n} 个链接`)}t.imageCss&&a.push(`章节图片：当前页面找到 ${document.querySelectorAll(t.imageCss).length} 张（目录页为 0 属正常）`),a.push(t.simpleRule?"图片解析：已自动生成":"图片解析函数：语法通过（未执行网络下载）"),e.textContent=a.join("\n"),e.classList.add("is-success")}catch(t){e.textContent=`测试失败：${t.message}`,e.classList.add("is-error")}}function Zt(){try{
const e=Ht(),t=v("userWebInfo",[]),n=Array.isArray(t)?t.slice():[];b.editRuleIndex>=0&&n[b.editRuleIndex]?n[b.editRuleIndex]=e:n.unshift(e),(0,r.po)("userWebInfo",n);const a=b.editRuleIndex>=0;Wt(),b.sourceMode=1,U(),F("sites"),Jt(a?"规则已更新，刷新目标页面后生效":"规则已保存，打开目标页面即可使用")}catch(e){Jt(e.message||"规则保存失败")}}function Yt(){const e=nn("ten-rule-text").value.trim();if(!e)return Jt("请先粘贴规则数组");try{const t=Function(`"use strict";return (${e})`)();if(!Array.isArray(t))throw new Error("规则必须是数组")
;const n=e=>(Array.isArray(e)?e:[e]).some(e=>String(e||"").trim());if(t.some(e=>!e||!n(e.domain)))throw new Error("规则域名不能为空");const a=t.map(e=>{const t={...e};return["getImgs","getComicInfo"].forEach(e=>{"function"==typeof t[e]&&(t[e]=t[e].toString())}),t}),i=v("userWebInfo",[]),o=Array.isArray(i)?i:[];(0,r.po)("userWebInfo",a.concat(o)),nn("ten-rule-text").value="",b.sourceMode=1,U(),F("sites"),Jt(`已导入 ${t.length} 条规则`)}catch(e){Jt("规则格式不正确")}}async function Kt(){
await nt("清空自定义规则","将删除全部已导入规则，此操作无法撤销。","全部清空")&&((0,r.po)("userWebInfo",[]),U(),Jt("导入规则已清空"))}async function Vt(){await nt("重置全部设置","界面、下载和规则设置都将恢复默认值。","确认重置")&&(await(0,r.zU)(),b.settings=f(),b.ready&&(P(),Jt("设置已重置")))}function Gt(e=(b.settings?b.settings.effectLevel:1)){const t=0===e?0:1===e?11:22,n=nn("ten-particle-field");if(b.particleCount===t&&n.childElementCount===t)return;b.particleCount=t;const r=["#5ff6ff","#5b8cff","#9c6cff","#ff5fac"];n.innerHTML=Array.from({length:t
},(e,t)=>`<i style="--x:${(37*t+11)%100}%;--y:${(61*t+7)%100}%;--s:${1+t%3}px;--tx:${13*t%34-16}px;--ty:${17*t%46-22}px;--d:${4+t%5}s;--delay:-${t%7}s;--c:${r[t%r.length]}"></i>`).join("")}function Xt(e){const t=e.target.closest(".ten-btn");if(!t||t.disabled||0===b.settings.effectLevel)return;const n=t.getBoundingClientRect(),r=document.createElement("span"),a=Math.max(n.width,n.height);r.className="ten-ripple",r.style.width=r.style.height=`${a}px`,r.style.left=e.clientX-n.left-a/2+"px",
r.style.top=e.clientY-n.top-a/2+"px",t.appendChild(r),r.addEventListener("animationend",()=>r.remove(),{once:!0})}function Jt(e,t=null){if(!b.ready)return;const n=nn("ten-toast"),r=nn("ten-toast-action");rn(nn("ten-toast-text"),e),b.toastUndo="function"==typeof t?t:null,r.hidden=!b.toastUndo,n.classList.add("is-show"),clearTimeout(b.toastTimer),b.toastTimer=setTimeout(()=>{n.classList.remove("is-show"),b.toastUndo=null,r.hidden=!0},b.toastUndo?6500:2200)}function Qt(){const e=b.toastUndo
;e&&(b.toastUndo=null,clearTimeout(b.toastTimer),nn("ten-toast-action").hidden=!0,e(),Jt("已撤销刚才的操作"))}function en(e){const t=e.downChapterName||e.chapterName||"未命名章节",n="failed"===e.status||"partial"===e.status||e.hasError,r=n?`${t} 下载结束，存在失败图片`:`${t} 下载完成`;if(!b.visible||document.hidden){if(b.settings.notifyComplete)try{GM_notification({title:n?"10漫画：下载存在错误":"10漫画：下载完成",text:r,timeout:6e3,silent:!1,onclick:()=>{O(),F("tasks")}})}catch(e){console.warn("10漫画：系统通知发送失败。",e)}}else Jt(r)}
function tn(e){return`<div class="ten-empty">${dn(e)}</div>`}function nn(e){return document.getElementById(e)}function rn(e,t){const n=String(t);e&&e.textContent!==n&&(e.textContent=n)}function an(e,t,n){e&&e.getAttribute(t)!==n&&e.setAttribute(t,n)}function on(e,t,n){e&&e.style.getPropertyValue(t)!==n&&e.style.setProperty(t,n)}function sn(e,t=document){return t.querySelector(e)}function cn(e,t=document){return Array.from(t.querySelectorAll(e))}function dn(e){
return String(null==e?"":e).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function ln(e){return dn(e).replace(/`/g,"&#96;")}})()})();

